/**
 * @packageDocumentation
 * @module api.functional.documents.form
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { CreateFormDocumentDto } from '../../../structures/CreateFormDocumentDto';
import type { Recordstringunknown } from '../../../structures/Recordstringunknown';
import type { UpdateFormDocumentDto } from '../../../structures/UpdateFormDocumentDto';
import type { mongoose } from '../../../structures/mongoose';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import typia from 'typia';
import type { Resolved, tags } from 'typia';

/**
 * @controller DocumentsController.createForm
 * @path POST /documents/form
 * @accessor api.functional.documents.form.createForm
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createForm(
  connection: IConnection,
  createFormDocumentDto: createForm.Body,
): Promise<createForm.Output> {
  typia.assert<typeof createFormDocumentDto>(createFormDocumentDto);
  return true === connection.simulate
    ? createForm.simulate(connection, createFormDocumentDto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            'Content-Type': 'application/json',
          },
        },
        {
          ...createForm.METADATA,
          template: createForm.METADATA.path,
          path: createForm.path(),
        },
        createFormDocumentDto,
      );
}
export namespace createForm {
  export type Body = CreateFormDocumentDto;
  export type Output = {
    _id: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>;
    patientId: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>;
    templateId: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>;
    data: Recordstringunknown;
  };

  export const METADATA = {
    method: 'POST',
    path: '/documents/form',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => '/documents/form';
  export const random = (): Resolved<{
    _id: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>;
    patientId: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>;
    templateId: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>;
    data: Recordstringunknown;
  }> =>
    typia.random<{
      _id: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>;
      patientId: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>;
      templateId: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>;
      data: Recordstringunknown;
    }>();
  export const simulate = (
    connection: IConnection,
    createFormDocumentDto: Body,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: 'application/json',
    });
    assert.body(() => typia.assert(createFormDocumentDto));
    return random();
  };
}

/**
 * @controller DocumentsController.updateForm
 * @path POST /documents/form/:id
 * @accessor api.functional.documents.form.updateForm
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateForm(
  connection: IConnection,
  id: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>,
  updateFormDocumentDto: updateForm.Body,
): Promise<updateForm.Output> {
  typia.assert<typeof id>(id);
  typia.assert<typeof updateFormDocumentDto>(updateFormDocumentDto);
  return true === connection.simulate
    ? updateForm.simulate(connection, id, updateFormDocumentDto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            'Content-Type': 'application/json',
          },
        },
        {
          ...updateForm.METADATA,
          template: updateForm.METADATA.path,
          path: updateForm.path(id),
        },
        updateFormDocumentDto,
      );
}
export namespace updateForm {
  export type Body = UpdateFormDocumentDto;
  export type Output = mongoose.UpdateWriteOpResult;

  export const METADATA = {
    method: 'POST',
    path: '/documents/form/:id',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (id: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>) =>
    `/documents/form/${encodeURIComponent(id?.toString() ?? 'null')}`;
  export const random = (): Resolved<mongoose.UpdateWriteOpResult> =>
    typia.random<mongoose.UpdateWriteOpResult>();
  export const simulate = (
    connection: IConnection,
    id: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>,
    updateFormDocumentDto: Body,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: 'application/json',
    });
    assert.param('id')(() => typia.assert(id));
    assert.body(() => typia.assert(updateFormDocumentDto));
    return random();
  };
}
