/**
 * @packageDocumentation
 * @module api.functional.documents.form
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { CreateFormDocumentDto } from '../../../structures/CreateFormDocumentDto';
import type { FormDocument_idMongoId } from '../../../structures/FormDocument_idMongoId';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import typia from 'typia';
import type { Resolved } from 'typia';

/**
 * @controller DocumentsController.createForm
 * @path POST /documents/form
 * @accessor api.functional.documents.form.createForm
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createForm(
  connection: IConnection,
  createFormDocumentDto: createForm.Body,
): Promise<createForm.Output> {
  typia.assert<typeof createFormDocumentDto>(createFormDocumentDto);
  return true === connection.simulate
    ? createForm.simulate(connection, createFormDocumentDto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            'Content-Type': 'application/json',
          },
        },
        {
          ...createForm.METADATA,
          template: createForm.METADATA.path,
          path: createForm.path(),
        },
        createFormDocumentDto,
      );
}
export namespace createForm {
  export type Body = CreateFormDocumentDto;
  export type Output = FormDocument_idMongoId;

  export const METADATA = {
    method: 'POST',
    path: '/documents/form',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => '/documents/form';
  export const random = (): Resolved<FormDocument_idMongoId> =>
    typia.random<FormDocument_idMongoId>();
  export const simulate = (
    connection: IConnection,
    createFormDocumentDto: Body,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: 'application/json',
    });
    assert.body(() => typia.assert(createFormDocumentDto));
    return random();
  };
}
