/**
 * @packageDocumentation
 * @module api.functional.Patient.page
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { Patient_idstring } from '../../../structures/Patient_idstring';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import type { Resolved } from 'typia';
import typia from 'typia';

/**
 * @controller PatientController.findPage
 * @path GET /Patient/page/:pageNumber/:pageSize
 * @accessor api.functional.Patient.page.findPage
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findPage(
  connection: IConnection,
  pageSize: number,
  pageNumber: number,
): Promise<findPage.Output> {
  return true === connection.simulate
    ? findPage.simulate(connection, pageSize, pageNumber)
    : PlainFetcher.fetch(connection, {
        ...findPage.METADATA,
        template: findPage.METADATA.path,
        path: findPage.path(pageSize, pageNumber),
      });
}
export namespace findPage {
  export type Output = Patient_idstring.o3[];

  export const METADATA = {
    method: 'GET',
    path: '/Patient/page/:pageNumber/:pageSize',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (pageSize: number, pageNumber: number) =>
    `/Patient/page/${encodeURIComponent(pageNumber?.toString() ?? 'null')}/${encodeURIComponent(pageSize?.toString() ?? 'null')}`;
  export const random = (): Resolved<Patient_idstring.o3[]> =>
    typia.random<Patient_idstring.o3[]>();
  export const simulate = (
    connection: IConnection,
    pageSize: number,
    pageNumber: number,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(pageSize, pageNumber),
      contentType: 'application/json',
    });
    assert.param('pageSize')(() => typia.assert(pageSize));
    assert.param('pageNumber')(() => typia.assert(pageNumber));
    return random();
  };
}
