/**
 * @packageDocumentation
 * @module api.functional.patient.page
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { PaginatedResponseDtoPatient_idstring } from '../../../structures/PaginatedResponseDtoPatient_idstring';
import type { Patient_idstring } from '../../../structures/Patient_idstring';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import typia from 'typia';
import type { Resolved } from 'typia';

/**
 * @controller PatientController.findPage
 * @path GET /patient/page/:pageNumber/:numberOfRows
 * @accessor api.functional.patient.page.findPage
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findPage(
  connection: IConnection,
  numberOfRows: number,
  pageNumber: number,
): Promise<findPage.Output> {
  typia.assert<typeof numberOfRows>(numberOfRows);
  typia.assert<typeof pageNumber>(pageNumber);
  return true === connection.simulate
    ? findPage.simulate(connection, numberOfRows, pageNumber)
    : PlainFetcher.fetch(connection, {
        ...findPage.METADATA,
        template: findPage.METADATA.path,
        path: findPage.path(numberOfRows, pageNumber),
      });
}
export namespace findPage {
  export type Output = PaginatedResponseDtoPatient_idstring;

  export const METADATA = {
    method: 'GET',
    path: '/patient/page/:pageNumber/:numberOfRows',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (numberOfRows: number, pageNumber: number) =>
    `/patient/page/${encodeURIComponent(pageNumber?.toString() ?? 'null')}/${encodeURIComponent(numberOfRows?.toString() ?? 'null')}`;
  export const random = (): Resolved<PaginatedResponseDtoPatient_idstring> =>
    typia.random<PaginatedResponseDtoPatient_idstring>();
  export const simulate = (
    connection: IConnection,
    numberOfRows: number,
    pageNumber: number,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(numberOfRows, pageNumber),
      contentType: 'application/json',
    });
    assert.param('numberOfRows')(() => typia.assert(numberOfRows));
    assert.param('pageNumber')(() => typia.assert(pageNumber));
    return random();
  };
}

/**
 * @controller PatientController.findPageByFilter
 * @path GET /patient/page/:pageNumber/:numberOfRows/:filter/:search
 * @accessor api.functional.patient.page.findPageByFilter
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findPageByFilter(
  connection: IConnection,
  numberOfRows: number,
  pageNumber: number,
  filter: string,
  search: string,
): Promise<findPageByFilter.Output> {
  typia.assert<typeof numberOfRows>(numberOfRows);
  typia.assert<typeof pageNumber>(pageNumber);
  typia.assert<typeof filter>(filter);
  typia.assert<typeof search>(search);
  return true === connection.simulate
    ? findPageByFilter.simulate(
        connection,
        numberOfRows,
        pageNumber,
        filter,
        search,
      )
    : PlainFetcher.fetch(connection, {
        ...findPageByFilter.METADATA,
        template: findPageByFilter.METADATA.path,
        path: findPageByFilter.path(numberOfRows, pageNumber, filter, search),
      });
}
export namespace findPageByFilter {
  export type Output = Patient_idstring.o4[];

  export const METADATA = {
    method: 'GET',
    path: '/patient/page/:pageNumber/:numberOfRows/:filter/:search',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    numberOfRows: number,
    pageNumber: number,
    filter: string,
    search: string,
  ) =>
    `/patient/page/${encodeURIComponent(pageNumber?.toString() ?? 'null')}/${encodeURIComponent(numberOfRows?.toString() ?? 'null')}/${encodeURIComponent(filter?.toString() ?? 'null')}/${encodeURIComponent(search?.toString() ?? 'null')}`;
  export const random = (): Resolved<Patient_idstring.o4[]> =>
    typia.random<Patient_idstring.o4[]>();
  export const simulate = (
    connection: IConnection,
    numberOfRows: number,
    pageNumber: number,
    filter: string,
    search: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(numberOfRows, pageNumber, filter, search),
      contentType: 'application/json',
    });
    assert.param('numberOfRows')(() => typia.assert(numberOfRows));
    assert.param('pageNumber')(() => typia.assert(pageNumber));
    assert.param('filter')(() => typia.assert(filter));
    assert.param('search')(() => typia.assert(search));
    return random();
  };
}
