import { CreateManualDto } from './dto/create-manual.dto';
import { MANUAL_TYPE, ManualService } from './manual.service';
import { getFilesFromRequest } from '@/utils/helpers';
import { TypedFormData, TypedRoute } from '@nestia/core';
import {
  BadRequestException,
  Controller,
  Req,
  Header,
  StreamableFile,
  Get,
} from '@nestjs/common';
import type { Request } from 'express';
import { remove } from 'fs-extra';

@Controller('manual')
export class ManualController {
  constructor(private readonly manualService: ManualService) {}

  @TypedRoute.Post()
  async create(
    @Req() request: Request,

    // This is a workaround for the issue where Nestia SDK does not support diskStorage in multer.
    // multer.diskStorage will store the uploaded file into temporary location and put the path in the request.
    @TypedFormData.Body(ManualService.getMulter) _: CreateManualDto,
  ): Promise<true> {
    const files = getFilesFromRequest(request);

    try {
      if (files.length !== 1 || files[0] === undefined) {
        throw new BadRequestException('Exactly one file must be uploaded.');
      }

      return await this.manualService.create(files[0]);
    } finally {
      // SAFETY: these files are temporary files generated by Multer.
      await Promise.all(files.map(async (file) => remove(file.path)));
    }
  }

  /**
   * @ignore
   * @description This endpoint is used to view the manual and the SDK does not support it.
   */
  @Get()
  @Header('Content-Type', MANUAL_TYPE)
  async find(): Promise<StreamableFile> {
    return this.manualService.find();
  }
}
