import { Config } from '@/utils/config';
import {
  BadRequestException,
  Injectable,
  NotFoundException,
  StreamableFile,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { move, createReadStream, access, constants } from 'fs-extra';
import multer, { diskStorage, Multer } from 'multer';
import { join } from 'node:path';
import typia from 'typia';

export const MANUAL_NAME = 'manual.pdf';
export const MANUAL_TYPE = 'application/pdf';

@Injectable()
export class ManualService {
  // This static property holds the Multer instance for handling file uploads.
  // Used by ManualController
  private static multerInstance?: Multer;
  public _filePath: string;

  constructor(private readonly configService: ConfigService<Config, true>) {
    this._filePath = this.configService.getOrThrow('DATA_PATH');

    // Initialize the Multer instance for handling file uploads if it hasn't been initialized yet.
    ManualService.multerInstance ??= multer({
      storage: diskStorage({ destination: this._filePath }),

      limits: { fileSize: this.configService.getOrThrow('MAX_FILE_SIZE') },
    });
  }

  // This static method returns the static Multer instance for handling file uploads.
  static getMulter(): multer.Multer {
    if (!ManualService.multerInstance) {
      throw new Error('Multer instance is not initialized.');
    }

    return ManualService.multerInstance;
  }

  // This method handles the creation of a new manual by moving the uploaded file to the designated location.
  async create(manual: Express.Multer.File): Promise<true> {
    if (manual.mimetype !== MANUAL_TYPE) {
      throw new BadRequestException(
        'Invalid file type. Only PDF files are allowed.',
      );
    }

    // Move the uploaded manual to the designated location with the specified name.
    // SAFETY: this file is a temporary file generated by Multer.
    await move(manual.path, join(this._filePath, MANUAL_NAME), {
      overwrite: true,
    });

    return true;
  }

  // This method retrieves the manual as a StreamableFile for viewing or downloading.
  async hasManual(): Promise<true | NodeJS.ErrnoException> {
    const manualPath = join(this._filePath, MANUAL_NAME);

    // Ensure that the manual file exists and is readable before attempting to create a StreamableFile.
    try {
      await access(manualPath, constants.R_OK);
      return true;
    } catch (e: unknown) {
      typia.assertGuard<NodeJS.ErrnoException>(e);

      return e;
    }
  }

  // This method retrieves the manual as a StreamableFile for viewing or downloading.
  async getManual(): Promise<StreamableFile> {
    // Ensure that the manual file exists and is readable before attempting to create a StreamableFile.
    if ((await this.hasManual()) !== true) {
      throw new NotFoundException(
        'Manual not found. Please upload a manual first.',
      );
    }

    // Create a read stream for the manual file and return it as a StreamableFile with appropriate headers.
    const file = createReadStream(join(this._filePath, MANUAL_NAME));
    return new StreamableFile(file, {
      type: MANUAL_TYPE,
      disposition: `inline; filename="${MANUAL_NAME}"`,
    });
  }
}
