/**
 * @packageDocumentation
 * @module api.functional.observations
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { CreateObservationDto } from '../../structures/CreateObservationDto';
import type { Observation_idstring } from '../../structures/Observation_idstring';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import typia from 'typia';
import type { Resolved } from 'typia';

export * as type from './type/index';

/**
 * @controller ObservationsController.create
 * @path POST /observations
 * @accessor api.functional.observations.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  createObservationDto: create.Body,
): Promise<create.Output> {
  typia.assert<typeof createObservationDto>(createObservationDto);
  return true === connection.simulate
    ? create.simulate(connection, createObservationDto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            'Content-Type': 'application/json',
          },
        },
        {
          ...create.METADATA,
          template: create.METADATA.path,
          path: create.path(),
        },
        createObservationDto,
      );
}
export namespace create {
  export type Body = CreateObservationDto;
  export type Output = Observation_idstring;

  export const METADATA = {
    method: 'POST',
    path: '/observations',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => '/observations';
  export const random = (): Resolved<Observation_idstring> =>
    typia.random<Observation_idstring>();
  export const simulate = (
    connection: IConnection,
    createObservationDto: Body,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: 'application/json',
    });
    assert.body(() => typia.assert(createObservationDto));
    return random();
  };
}

/**
 * @controller ObservationsController.findAllObservations
 * @path GET /observations/:patientId
 * @accessor api.functional.observations.findAllObservations
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAllObservations(
  connection: IConnection,
  patientId: string,
): Promise<findAllObservations.Output> {
  typia.assert<typeof patientId>(patientId);
  return true === connection.simulate
    ? findAllObservations.simulate(connection, patientId)
    : PlainFetcher.fetch(connection, {
        ...findAllObservations.METADATA,
        template: findAllObservations.METADATA.path,
        path: findAllObservations.path(patientId),
      });
}
export namespace findAllObservations {
  export type Output = Observation_idstring.o1[];

  export const METADATA = {
    method: 'GET',
    path: '/observations/:patientId',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (patientId: string) =>
    `/observations/${encodeURIComponent(patientId?.toString() ?? 'null')}`;
  export const random = (): Resolved<Observation_idstring.o1[]> =>
    typia.random<Observation_idstring.o1[]>();
  export const simulate = (
    connection: IConnection,
    patientId: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(patientId),
      contentType: 'application/json',
    });
    assert.param('patientId')(() => typia.assert(patientId));
    return random();
  };
}
