/**
 * @packageDocumentation
 * @module api.functional.user
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { CreateUserDto } from '../../structures/CreateUserDto';
import type { UpdateUserDto } from '../../structures/UpdateUserDto';
import type { User_idstring } from '../../structures/User_idstring';
import type { mongoose } from '../../structures/mongoose';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import type { Resolved } from 'typia';
import typia from 'typia';

export * as page from './page/index';

/**
 * @controller UserController.create
 * @path POST /user
 * @accessor api.functional.user.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  createUserDto: create.Body,
): Promise<create.Output> {
  return true === connection.simulate
    ? create.simulate(connection, createUserDto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            'Content-Type': 'application/json',
          },
        },
        {
          ...create.METADATA,
          template: create.METADATA.path,
          path: create.path(),
        },
        createUserDto,
      );
}
export namespace create {
  export type Body = CreateUserDto;
  export type Output = User_idstring;

  export const METADATA = {
    method: 'POST',
    path: '/user',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => '/user';
  export const random = (): Resolved<User_idstring> =>
    typia.random<User_idstring>();
  export const simulate = (
    connection: IConnection,
    createUserDto: Body,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: 'application/json',
    });
    assert.body(() => typia.assert(createUserDto));
    return random();
  };
}

/**
 * @controller UserController.findAll
 * @path GET /user
 * @accessor api.functional.user.findAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
): Promise<findAll.Output> {
  return true === connection.simulate
    ? findAll.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...findAll.METADATA,
        template: findAll.METADATA.path,
        path: findAll.path(),
      });
}
export namespace findAll {
  export type Output = User_idstring.o1[];

  export const METADATA = {
    method: 'GET',
    path: '/user',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => '/user';
  export const random = (): Resolved<User_idstring.o1[]> =>
    typia.random<User_idstring.o1[]>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}

/**
 * @controller UserController.findOne
 * @path GET /user/:id
 * @accessor api.functional.user.findOne
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findOne(
  connection: IConnection,
  id: string,
): Promise<findOne.Output> {
  return true === connection.simulate
    ? findOne.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...findOne.METADATA,
        template: findOne.METADATA.path,
        path: findOne.path(id),
      });
}
export namespace findOne {
  export type Output = null | User_idstring.o2;

  export const METADATA = {
    method: 'GET',
    path: '/user/:id',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/user/${encodeURIComponent(id?.toString() ?? 'null')}`;
  export const random = (): Resolved<null | User_idstring.o2> =>
    typia.random<null | User_idstring.o2>();
  export const simulate = (connection: IConnection, id: string): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: 'application/json',
    });
    assert.param('id')(() => typia.assert(id));
    return random();
  };
}

/**
 * @controller UserController.update
 * @path PATCH /user/:id
 * @accessor api.functional.user.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  updateUserDto: update.Body,
): Promise<update.Output> {
  return true === connection.simulate
    ? update.simulate(connection, id, updateUserDto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            'Content-Type': 'application/json',
          },
        },
        {
          ...update.METADATA,
          template: update.METADATA.path,
          path: update.path(id),
        },
        updateUserDto,
      );
}
export namespace update {
  export type Body = UpdateUserDto;
  export type Output = mongoose.UpdateWriteOpResult;

  export const METADATA = {
    method: 'PATCH',
    path: '/user/:id',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/user/${encodeURIComponent(id?.toString() ?? 'null')}`;
  export const random = (): Resolved<mongoose.UpdateWriteOpResult> =>
    typia.random<mongoose.UpdateWriteOpResult>();
  export const simulate = (
    connection: IConnection,
    id: string,
    updateUserDto: Body,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: 'application/json',
    });
    assert.param('id')(() => typia.assert(id));
    assert.body(() => typia.assert(updateUserDto));
    return random();
  };
}
