/**
 * @packageDocumentation
 * @module api.functional.documents
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { FindDocumentDto } from '../../structures/FindDocumentDto';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import type { Resolved, tags } from 'typia';
import typia from 'typia';

export * as file from './file/index';
export * as form from './form/index';

/**
 * @controller DocumentsController.findOne
 * @path GET /documents/:id
 * @accessor api.functional.documents.findOne
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findOne(
  connection: IConnection,
  id: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>,
): Promise<findOne.Output> {
  typia.assert<typeof id>(id);
  return true === connection.simulate
    ? findOne.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...findOne.METADATA,
        template: findOne.METADATA.path,
        path: findOne.path(id),
      });
}
export namespace findOne {
  export type Output = null | FindDocumentDto;

  export const METADATA = {
    method: 'GET',
    path: '/documents/:id',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>) =>
    `/documents/${encodeURIComponent(id?.toString() ?? 'null')}`;
  export const random = (): Resolved<null | FindDocumentDto> =>
    typia.random<null | FindDocumentDto>();
  export const simulate = (
    connection: IConnection,
    id: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: 'application/json',
    });
    assert.param('id')(() => typia.assert(id));
    return random();
  };
}
