/**
 * @packageDocumentation
 * @module api.functional.user.nurses
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { NurseListDto_idstring } from '../../../structures/NurseListDto_idstring';
import type { IConnection } from '@nestia/fetcher';
import { PlainFetcher } from '@nestia/fetcher';
import type { Resolved } from 'typia';
import typia from 'typia';

/**
 * @controller UserController.findNurses
 * @path GET /user/nurses
 * @accessor api.functional.user.nurses.findNurses
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findNurses(
  connection: IConnection,
): Promise<findNurses.Output> {
  return true === connection.simulate
    ? findNurses.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...findNurses.METADATA,
        template: findNurses.METADATA.path,
        path: findNurses.path(),
      });
}
export namespace findNurses {
  export type Output = NurseListDto_idstring[];

  export const METADATA = {
    method: 'GET',
    path: '/user/nurses',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => '/user/nurses';
  export const random = (): Resolved<NurseListDto_idstring[]> =>
    typia.random<NurseListDto_idstring[]>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
