/**
 * @packageDocumentation
 * @module api.functional.emergency_contacts
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { CreateEmergencyContactDto } from '../../structures/CreateEmergencyContactDto';
import type { EmergencyContact_idstring } from '../../structures/EmergencyContact_idstring';
import type { UpdateEmergencyContactDto } from '../../structures/UpdateEmergencyContactDto';
import type { mongoose } from '../../structures/mongoose';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import type { Resolved } from 'typia';
import typia from 'typia';

/**
 * @controller EmergencyContactController.create
 * @path POST /emergency-contacts
 * @accessor api.functional.emergency_contacts.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  createEmergencyContactDto: create.Body,
): Promise<create.Output> {
  return true === connection.simulate
    ? create.simulate(connection, createEmergencyContactDto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            'Content-Type': 'application/json',
          },
        },
        {
          ...create.METADATA,
          template: create.METADATA.path,
          path: create.path(),
        },
        createEmergencyContactDto,
      );
}
export namespace create {
  export type Body = CreateEmergencyContactDto;
  export type Output = EmergencyContact_idstring;

  export const METADATA = {
    method: 'POST',
    path: '/emergency-contacts',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => '/emergency-contacts';
  export const random = (): Resolved<EmergencyContact_idstring> =>
    typia.random<EmergencyContact_idstring>();
  export const simulate = (
    connection: IConnection,
    createEmergencyContactDto: Body,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: 'application/json',
    });
    assert.body(() => typia.assert(createEmergencyContactDto));
    return random();
  };
}

/**
 * @controller EmergencyContactController.findPatientEmergncyContacts
 * @path GET /emergency-contacts/:id
 * @accessor api.functional.emergency_contacts.findPatientEmergncyContacts
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findPatientEmergncyContacts(
  connection: IConnection,
  id: string,
): Promise<findPatientEmergncyContacts.Output> {
  return true === connection.simulate
    ? findPatientEmergncyContacts.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...findPatientEmergncyContacts.METADATA,
        template: findPatientEmergncyContacts.METADATA.path,
        path: findPatientEmergncyContacts.path(id),
      });
}
export namespace findPatientEmergncyContacts {
  export type Output = EmergencyContact_idstring.o1[];

  export const METADATA = {
    method: 'GET',
    path: '/emergency-contacts/:id',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/emergency-contacts/${encodeURIComponent(id?.toString() ?? 'null')}`;
  export const random = (): Resolved<EmergencyContact_idstring.o1[]> =>
    typia.random<EmergencyContact_idstring.o1[]>();
  export const simulate = (connection: IConnection, id: string): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: 'application/json',
    });
    assert.param('id')(() => typia.assert(id));
    return random();
  };
}

/**
 * @controller EmergencyContactController.update
 * @path PATCH /emergency-contacts/:id
 * @accessor api.functional.emergency_contacts.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  updateEmergencyContactDto: update.Body,
): Promise<update.Output> {
  return true === connection.simulate
    ? update.simulate(connection, id, updateEmergencyContactDto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            'Content-Type': 'application/json',
          },
        },
        {
          ...update.METADATA,
          template: update.METADATA.path,
          path: update.path(id),
        },
        updateEmergencyContactDto,
      );
}
export namespace update {
  export type Body = UpdateEmergencyContactDto;
  export type Output = mongoose.UpdateWriteOpResult;

  export const METADATA = {
    method: 'PATCH',
    path: '/emergency-contacts/:id',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/emergency-contacts/${encodeURIComponent(id?.toString() ?? 'null')}`;
  export const random = (): Resolved<mongoose.UpdateWriteOpResult> =>
    typia.random<mongoose.UpdateWriteOpResult>();
  export const simulate = (
    connection: IConnection,
    id: string,
    updateEmergencyContactDto: Body,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: 'application/json',
    });
    assert.param('id')(() => typia.assert(id));
    assert.body(() => typia.assert(updateEmergencyContactDto));
    return random();
  };
}
