/**
 * @packageDocumentation
 * @module api.functional.observations.type
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { Observation_idstring } from '../../../structures/Observation_idstring';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import type { Resolved } from 'typia';
import typia from 'typia';

/**
 * @controller ObservationsController.findByType
 * @path GET /observations/:id/type
 * @accessor api.functional.observations.type.findByType
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findByType(
  connection: IConnection,
  id: string,
  type:
    | 'OXYGEN_RATE'
    | 'RESPIRATION_RATE'
    | 'BLOOD_PRESSURE'
    | 'HEART_RATE'
    | 'TEMPERATURE'
    | 'WEIGHT'
    | 'BLOOD_GLUCOSE_LEVELS'
    | 'NEUROLOGICAL_OBSERVATION_CHART'
    | 'BOWEL_OUTPUT'
    | 'URINE_OUTPUT',
): Promise<findByType.Output> {
  return true === connection.simulate
    ? findByType.simulate(connection, id, type)
    : PlainFetcher.fetch(connection, {
        ...findByType.METADATA,
        template: findByType.METADATA.path,
        path: findByType.path(id, type),
      });
}
export namespace findByType {
  export type Output = Observation_idstring.o2[];

  export const METADATA = {
    method: 'GET',
    path: '/observations/:id/type',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    id: string,
    type:
      | 'OXYGEN_RATE'
      | 'RESPIRATION_RATE'
      | 'BLOOD_PRESSURE'
      | 'HEART_RATE'
      | 'TEMPERATURE'
      | 'WEIGHT'
      | 'BLOOD_GLUCOSE_LEVELS'
      | 'NEUROLOGICAL_OBSERVATION_CHART'
      | 'BOWEL_OUTPUT'
      | 'URINE_OUTPUT',
  ) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries({
      type: type,
    } as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/observations/${encodeURIComponent(id?.toString() ?? 'null')}/type`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): Resolved<Observation_idstring.o2[]> =>
    typia.random<Observation_idstring.o2[]>();
  export const simulate = (
    connection: IConnection,
    id: string,
    type:
      | 'OXYGEN_RATE'
      | 'RESPIRATION_RATE'
      | 'BLOOD_PRESSURE'
      | 'HEART_RATE'
      | 'TEMPERATURE'
      | 'WEIGHT'
      | 'BLOOD_GLUCOSE_LEVELS'
      | 'NEUROLOGICAL_OBSERVATION_CHART'
      | 'BOWEL_OUTPUT'
      | 'URINE_OUTPUT',
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id, type),
      contentType: 'application/json',
    });
    assert.param('id')(() => typia.assert(id));
    assert.query(() => typia.assert(type));
    return random();
  };
}
