/**
 * @packageDocumentation
 * @module api.functional.observations.type
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { Observation_idstring } from '../../../structures/Observation_idstring';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import typia from 'typia';
import type { Resolved } from 'typia';

/**
 * @controller ObservationsController.findByType
 * @path GET /observations/:patientId/type
 * @accessor api.functional.observations.type.findByType
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findByType(
  connection: IConnection,
  patientId: string,
  query: findByType.Query,
): Promise<findByType.Output> {
  typia.assert<typeof patientId>(patientId);
  typia.assert<typeof query>(query);
  return true === connection.simulate
    ? findByType.simulate(connection, patientId, query)
    : PlainFetcher.fetch(connection, {
        ...findByType.METADATA,
        template: findByType.METADATA.path,
        path: findByType.path(patientId, query),
      });
}
export namespace findByType {
  export type Query = {
    observationType:
      | 'OXYGEN_RATE'
      | 'RESPIRATION_RATE'
      | 'BLOOD_PRESSURE'
      | 'HEART_RATE'
      | 'TEMPERATURE'
      | 'WEIGHT'
      | 'BLOOD_GLUCOSE_LEVELS'
      | 'NEUROLOGICAL_OBSERVATION_CHART'
      | 'BOWEL_OUTPUT'
      | 'URINE_OUTPUT';
  };
  export type Output = Observation_idstring.o2[];

  export const METADATA = {
    method: 'GET',
    path: '/observations/:patientId/type',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (patientId: string, query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/observations/${encodeURIComponent(patientId?.toString() ?? 'null')}/type`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): Resolved<Observation_idstring.o2[]> =>
    typia.random<Observation_idstring.o2[]>();
  export const simulate = (
    connection: IConnection,
    patientId: string,
    query: Query,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(patientId, query),
      contentType: 'application/json',
    });
    assert.param('patientId')(() => typia.assert(patientId));
    assert.query(() => typia.assert(query));
    return random();
  };
}
