/**
 * @packageDocumentation
 * @module api.functional.user.page
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { User_idstring } from '../../../structures/User_idstring';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import type { Resolved } from 'typia';
import typia from 'typia';

/**
 * @controller UserController.findPage
 * @path GET /user/page/:pageNumber/:pageSize
 * @accessor api.functional.user.page.findPage
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findPage(
  connection: IConnection,
  pageNumber: number,
  pageSize: number,
): Promise<findPage.Output> {
  return true === connection.simulate
    ? findPage.simulate(connection, pageNumber, pageSize)
    : PlainFetcher.fetch(connection, {
        ...findPage.METADATA,
        template: findPage.METADATA.path,
        path: findPage.path(pageNumber, pageSize),
      });
}
export namespace findPage {
  export type Output = User_idstring.o3[];

  export const METADATA = {
    method: 'GET',
    path: '/user/page/:pageNumber/:pageSize',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (pageNumber: number, pageSize: number) =>
    `/user/page/${encodeURIComponent(pageNumber?.toString() ?? 'null')}/${encodeURIComponent(pageSize?.toString() ?? 'null')}`;
  export const random = (): Resolved<User_idstring.o3[]> =>
    typia.random<User_idstring.o3[]>();
  export const simulate = (
    connection: IConnection,
    pageNumber: number,
    pageSize: number,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(pageNumber, pageSize),
      contentType: 'application/json',
    });
    assert.param('pageNumber')(() => typia.assert(pageNumber));
    assert.param('pageSize')(() => typia.assert(pageSize));
    return random();
  };
}
