/**
 * @packageDocumentation
 * @module api.functional.templates.type
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { Template_idMongoId } from '../../../structures/Template_idMongoId';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import typia from 'typia';
import type { Resolved } from 'typia';

/**
 * @controller TemplatesController.findTemplatesWithType
 * @path GET /templates/type/:type
 * @accessor api.functional.templates.type.findTemplatesWithType
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findTemplatesWithType(
  connection: IConnection,
  type: 'Long Term' | 'Short Term' | 'Palliative' | 'Daycare',
): Promise<findTemplatesWithType.Output> {
  typia.assert<typeof type>(type);
  return true === connection.simulate
    ? findTemplatesWithType.simulate(connection, type)
    : PlainFetcher.fetch(connection, {
        ...findTemplatesWithType.METADATA,
        template: findTemplatesWithType.METADATA.path,
        path: findTemplatesWithType.path(type),
      });
}
export namespace findTemplatesWithType {
  export type Output = Template_idMongoId.o2[];

  export const METADATA = {
    method: 'GET',
    path: '/templates/type/:type',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    type: 'Long Term' | 'Short Term' | 'Palliative' | 'Daycare',
  ) => `/templates/type/${encodeURIComponent(type?.toString() ?? 'null')}`;
  export const random = (): Resolved<Template_idMongoId.o2[]> =>
    typia.random<Template_idMongoId.o2[]>();
  export const simulate = (
    connection: IConnection,
    type: 'Long Term' | 'Short Term' | 'Palliative' | 'Daycare',
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(type),
      contentType: 'application/json',
    });
    assert.param('type')(() => typia.assert(type));
    return random();
  };
}
