'use client';

import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { createContext, useEffect, type JSX, type ReactNode } from 'react';
import { TypeGuardError } from 'typia';
import { useLocalStorage, useIsClient } from 'usehooks-ts';

export const MAX_RETRIES = 3;

export const APIUrlContext = createContext<string>('');
export const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      // Disable retries for TypeGuardError
      // TypeGuardError is generated by @rehua/sdk and typia type checking
      retry: (failureCount, error): boolean => {
        if (error instanceof TypeGuardError) {
          return false;
        }

        return failureCount < MAX_RETRIES;
      },
    },
  },
});

export default function Providers({
  children,
}: Readonly<{ children: ReactNode }>): JSX.Element {
  const isClient = useIsClient();
  const [apiUrl, setApiUrl] = useLocalStorage<string>('apiUrl', '', {
    serializer: (d) => d,
    deserializer: (d) => d,
  });

  useEffect(() => {
    if (apiUrl.trim() === '') {
      const url = new URL('/api', globalThis.location.href);
      setApiUrl(url.href.replace(/\/$/, ''));
    }

    if (apiUrl.trim() !== apiUrl) {
      setApiUrl((s) => s.trim());
    }

    if (apiUrl.endsWith('/')) {
      setApiUrl((s) => s.replace(/\/$/, ''));
    }
  }, [apiUrl, setApiUrl]);

  if (!isClient || apiUrl.trim() === '') {
    return <h1>Loading...</h1>;
  }

  return (
    <QueryClientProvider client={queryClient}>
      <APIUrlContext value={apiUrl}>{children}</APIUrlContext>
      <ReactQueryDevtools />
    </QueryClientProvider>
  );
}
