'use client';

import { sessionStorageGetUserInfo } from './utils/auth';
import { isTesting } from './utils/env';
import { HttpError } from '@rehua/sdk';
import { refresh } from '@rehua/sdk/functional/auth';
import {
  QueryClient,
  QueryClientProvider,
  queryOptions,
  useQuery,
} from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { useRouter } from 'next/navigation';
import { createContext, useEffect, type JSX, type ReactNode } from 'react';
import { TypeGuardError } from 'typia';
import { useLocalStorage, useIsClient } from 'usehooks-ts';

export const MAX_RETRIES = 3;

export const APIUrlContext = createContext<string>('');
export const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: (failureCount, error): boolean => {
        // Disable retries for TypeGuardError
        // TypeGuardError is generated by @rehua/sdk and typia type checking
        if (error instanceof TypeGuardError) {
          return false;
        }

        if (error instanceof HttpError) {
          switch (error.status) {
            case 401:
              return false; // Unauthorized, do not retry
            case 403:
              return false; // Forbidden, do not retry
            case 404:
              return false; // Not Found, do not retry
            default:
              break;
          }
        }

        return failureCount < MAX_RETRIES;
      },
    },
  },
});

// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
export function useRefreshOptions(host: string) {
  return queryOptions({
    queryKey: [refresh.path(), host],
    queryFn: async () =>
      refresh({
        host: host,
        simulate: isTesting,
        options: { credentials: 'include' },
      }),

    // eslint-disable-next-line sonarjs/function-return-type
    refetchInterval: (query): number | false => {
      const error = query.state.error;
      if (error instanceof HttpError && error.status === 401) {
        // If the error is 401 Unauthorized, do not retry
        return false;
      }

      // Refresh the token every 2.5 minutes
      // if there is no error or if the error is not 401 Unauthorized
      return 2.5 * 60 * 1000;
    },
  });
}

export default function Providers({
  children,
}: Readonly<{ children: ReactNode }>): JSX.Element {
  const isClient = useIsClient();
  const [apiUrl, setApiUrl] = useLocalStorage<string>('apiUrl', '', {
    serializer: (d) => d,
    deserializer: (d) => d,
  });

  useEffect(() => {
    if (apiUrl.trim() === '') {
      const url = new URL('/api', globalThis.location.href);
      setApiUrl(url.href.replace(/\/$/, ''));
    }

    if (apiUrl.trim() !== apiUrl) {
      setApiUrl((s) => s.trim());
    }

    if (apiUrl.endsWith('/')) {
      setApiUrl((s) => s.replace(/\/$/, ''));
    }
  }, [apiUrl, setApiUrl]);

  const refreshOptions = useRefreshOptions(apiUrl);
  const { error } = useQuery(refreshOptions, queryClient);

  const router = useRouter();

  useEffect(() => {
    if (!isClient) {
      return;
    } else if (
      (error instanceof HttpError && error.status === 401) ||
      // TODO: change it to a proper way to detect login status
      sessionStorageGetUserInfo().userName === ''
    ) {
      // If the user is not authenticated, redirect to the login page
      router.push('/auth/login');
    }
  }, [error, isClient, router]);

  if (!isClient || apiUrl.trim() === '') {
    return <h1>Loading...</h1>;
  }

  return (
    <QueryClientProvider client={queryClient}>
      <APIUrlContext value={apiUrl}>{children}</APIUrlContext>
      <ReactQueryDevtools />
    </QueryClientProvider>
  );
}
