/**
 * @packageDocumentation
 * @module api.functional.templates
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { CreateTemplateDto } from '../../structures/CreateTemplateDto';
import type { Template_idMongoId } from '../../structures/Template_idMongoId';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import typia from 'typia';
import type { Resolved } from 'typia';

export * as id from './id/index';
export * as type from './type/index';

/**
 * @controller TemplatesController.create
 * @path POST /templates
 * @accessor api.functional.templates.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  createTemplateDto: create.Body,
): Promise<create.Output> {
  typia.assert<typeof createTemplateDto>(createTemplateDto);
  return true === connection.simulate
    ? create.simulate(connection, createTemplateDto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            'Content-Type': 'application/json',
          },
        },
        {
          ...create.METADATA,
          template: create.METADATA.path,
          path: create.path(),
        },
        createTemplateDto,
      );
}
export namespace create {
  export type Body = CreateTemplateDto;
  export type Output = Template_idMongoId;

  export const METADATA = {
    method: 'POST',
    path: '/templates',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => '/templates';
  export const random = (): Resolved<Template_idMongoId> =>
    typia.random<Template_idMongoId>();
  export const simulate = (
    connection: IConnection,
    createTemplateDto: Body,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: 'application/json',
    });
    assert.body(() => typia.assert(createTemplateDto));
    return random();
  };
}
