/**
 * @packageDocumentation
 * @module api.functional.templates
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { CreateTemplateDto } from '../../structures/CreateTemplateDto';
import type { Template_idstring } from '../../structures/Template_idstring';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import type { Resolved } from 'typia';
import typia from 'typia';

/**
 * @controller TemplatesController.create
 * @path POST /templates
 * @accessor api.functional.templates.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  createTemplateDto: create.Body,
): Promise<create.Output> {
  return true === connection.simulate
    ? create.simulate(connection, createTemplateDto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            'Content-Type': 'application/json',
          },
        },
        {
          ...create.METADATA,
          template: create.METADATA.path,
          path: create.path(),
        },
        createTemplateDto,
      );
}
export namespace create {
  export type Body = CreateTemplateDto;
  export type Output = Template_idstring;

  export const METADATA = {
    method: 'POST',
    path: '/templates',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => '/templates';
  export const random = (): Resolved<Template_idstring> =>
    typia.random<Template_idstring>();
  export const simulate = (
    connection: IConnection,
    createTemplateDto: Body,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: 'application/json',
    });
    assert.body(() => typia.assert(createTemplateDto));
    return random();
  };
}

/**
 * @controller TemplatesController.findOne
 * @path GET /templates/:id
 * @accessor api.functional.templates.findOne
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findOne(
  connection: IConnection,
  id: string,
): Promise<findOne.Output> {
  return true === connection.simulate
    ? findOne.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...findOne.METADATA,
        template: findOne.METADATA.path,
        path: findOne.path(id),
      });
}
export namespace findOne {
  export type Output = null | Template_idstring.o1;

  export const METADATA = {
    method: 'GET',
    path: '/templates/:id',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/templates/${encodeURIComponent(id?.toString() ?? 'null')}`;
  export const random = (): Resolved<null | Template_idstring.o1> =>
    typia.random<null | Template_idstring.o1>();
  export const simulate = (connection: IConnection, id: string): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: 'application/json',
    });
    assert.param('id')(() => typia.assert(id));
    return random();
  };
}

/**
 * @controller TemplatesController.findAll
 * @path GET /templates
 * @accessor api.functional.templates.findAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
): Promise<findAll.Output> {
  return true === connection.simulate
    ? findAll.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...findAll.METADATA,
        template: findAll.METADATA.path,
        path: findAll.path(),
      });
}
export namespace findAll {
  export type Output = Template_idstring.o2[];

  export const METADATA = {
    method: 'GET',
    path: '/templates',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => '/templates';
  export const random = (): Resolved<Template_idstring.o2[]> =>
    typia.random<Template_idstring.o2[]>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}

/**
 * @controller TemplatesController.remove
 * @path DELETE /templates/:id
 * @accessor api.functional.templates.remove
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function remove(
  connection: IConnection,
  id: string,
): Promise<remove.Output> {
  return true === connection.simulate
    ? remove.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...remove.METADATA,
        template: remove.METADATA.path,
        path: remove.path(id),
      });
}
export namespace remove {
  export type Output = null | Template_idstring.o3;

  export const METADATA = {
    method: 'DELETE',
    path: '/templates/:id',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/templates/${encodeURIComponent(id?.toString() ?? 'null')}`;
  export const random = (): Resolved<null | Template_idstring.o3> =>
    typia.random<null | Template_idstring.o3>();
  export const simulate = (connection: IConnection, id: string): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: 'application/json',
    });
    assert.param('id')(() => typia.assert(id));
    return random();
  };
}
