/**
 * @packageDocumentation
 * @module api.functional.templates
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { CreateTemplateDto } from '../../structures/CreateTemplateDto';
import type { Template_idMongoId } from '../../structures/Template_idMongoId';
import type { UpdateStatusDto } from '../../structures/UpdateStatusDto';
import type { mongoose } from '../../structures/mongoose';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import typia from 'typia';
import type { Resolved } from 'typia';

export * as id from './id/index';
export * as page from './page/index';
export * as type from './type/index';

/**
 * @controller TemplatesController.create
 * @path POST /templates
 * @accessor api.functional.templates.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  createTemplateDto: create.Body,
): Promise<create.Output> {
  typia.assert<typeof createTemplateDto>(createTemplateDto);
  return true === connection.simulate
    ? create.simulate(connection, createTemplateDto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            'Content-Type': 'application/json',
          },
        },
        {
          ...create.METADATA,
          template: create.METADATA.path,
          path: create.path(),
        },
        createTemplateDto,
      );
}
export namespace create {
  export type Body = CreateTemplateDto;
  export type Output = Template_idMongoId;

  export const METADATA = {
    method: 'POST',
    path: '/templates',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => '/templates';
  export const random = (): Resolved<Template_idMongoId> =>
    typia.random<Template_idMongoId>();
  export const simulate = (
    connection: IConnection,
    createTemplateDto: Body,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: 'application/json',
    });
    assert.body(() => typia.assert(createTemplateDto));
    return random();
  };
}

/**
 * @controller TemplatesController.update
 * @path PATCH /templates/:id
 * @accessor api.functional.templates.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  updateDto: update.Body,
): Promise<update.Output> {
  typia.assert<typeof id>(id);
  typia.assert<typeof updateDto>(updateDto);
  return true === connection.simulate
    ? update.simulate(connection, id, updateDto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            'Content-Type': 'application/json',
          },
        },
        {
          ...update.METADATA,
          template: update.METADATA.path,
          path: update.path(id),
        },
        updateDto,
      );
}
export namespace update {
  export type Body = UpdateStatusDto;
  export type Output = mongoose.UpdateWriteOpResult;

  export const METADATA = {
    method: 'PATCH',
    path: '/templates/:id',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/templates/${encodeURIComponent(id?.toString() ?? 'null')}`;
  export const random = (): Resolved<mongoose.UpdateWriteOpResult> =>
    typia.random<mongoose.UpdateWriteOpResult>();
  export const simulate = (
    connection: IConnection,
    id: string,
    updateDto: Body,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: 'application/json',
    });
    assert.param('id')(() => typia.assert(id));
    assert.body(() => typia.assert(updateDto));
    return random();
  };
}
