/**
 * @packageDocumentation
 * @module api.functional.manual.exists
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from '@nestia/fetcher';
import { PlainFetcher } from '@nestia/fetcher';
import type { Resolved } from 'typia';
import typia from 'typia';

/**
 * @description This endpoint is used to check if a manual exists.
 * @controller ManualController.hasManual
 * @path GET /manual/exists
 * @accessor api.functional.manual.exists.hasManual
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function hasManual(
  connection: IConnection,
): Promise<hasManual.Output> {
  return true === connection.simulate
    ? hasManual.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...hasManual.METADATA,
        template: hasManual.METADATA.path,
        path: hasManual.path(),
      });
}
export namespace hasManual {
  export type Output = boolean;

  export const METADATA = {
    method: 'GET',
    path: '/manual/exists',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => '/manual/exists';
  export const random = (): Resolved<boolean> => typia.random<boolean>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
