export type UpdatePatientDto = {
  firstName?: undefined | string;
  lastName?: undefined | string;
  dob?: undefined | string;
  address?: undefined | string;
  nhi?: undefined | number;
  dateAdmitted?: undefined | string;
  gpNameAndMedicalCenter?: undefined | string;
  nurse?: undefined | string;
  roomNumber?: undefined | number;
  status?: undefined | string;
  email?: undefined | string;
  homePhoneNumber?: undefined | string;
  gender?: undefined | string;
  primaryLanguage?: undefined | string;
  maritalStatus?: undefined | string;
  ethnicity?: undefined | string;
  allergies?: undefined | string;
  pfp?: undefined | string;
  funding?: undefined | string;
  tod?: undefined | string;
  id?: undefined | string;
};
