services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:24-trixie@sha256:0cbad76d1987fd35fd78cbc58cbe8c2aa93a8daa45411e52c6c6b63ea2dae202
    volumes:
      - ..:/workspace:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: mongo:8.3@sha256:48a009d2d8007e92d6d7e8baa31713cd11c48c06e827e856240e5a1d319b49d9
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
      - mongo_config:/data/configdb

volumes:
  mongodb-data:
  mongo_config:
