/**
 * @packageDocumentation
 * @module api.functional.observations.type.startDate.endDate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { Observation_idstring } from '../../../../../structures/Observation_idstring';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import typia from 'typia';
import type { Resolved } from 'typia';

/**
 * @controller ObservationsController.findObservationByDateRange
 * @path GET /observations/:id/type/startDate/endDate
 * @accessor api.functional.observations.type.startDate.endDate.findObservationByDateRange
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findObservationByDateRange(
  connection: IConnection,
  id: string,
  query: findObservationByDateRange.Query,
): Promise<findObservationByDateRange.Output> {
  typia.assert<typeof id>(id);
  typia.assert<typeof query>(query);
  return true === connection.simulate
    ? findObservationByDateRange.simulate(connection, id, query)
    : PlainFetcher.fetch(connection, {
        ...findObservationByDateRange.METADATA,
        template: findObservationByDateRange.METADATA.path,
        path: findObservationByDateRange.path(id, query),
      });
}
export namespace findObservationByDateRange {
  export type Query = {
    type:
      | 'RUNNING_NOTES'
      | 'OXYGEN_RATE'
      | 'RESPIRATION_RATE'
      | 'BLOOD_PRESSURE'
      | 'HEART_RATE'
      | 'TEMPERATURE'
      | 'WEIGHT'
      | 'BLOOD_GLUCOSE_LEVELS'
      | 'NEUROLOGICAL_OBSERVATION_CHART'
      | 'BOWEL_OUTPUT'
      | 'URINE_OUTPUT';
    startDate: string;
    endDate: string;
  };
  export type Output = Observation_idstring.o3[];

  export const METADATA = {
    method: 'GET',
    path: '/observations/:id/type/startDate/endDate',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string, query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/observations/${encodeURIComponent(id?.toString() ?? 'null')}/type/startDate/endDate`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): Resolved<Observation_idstring.o3[]> =>
    typia.random<Observation_idstring.o3[]>();
  export const simulate = (
    connection: IConnection,
    id: string,
    query: Query,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id, query),
      contentType: 'application/json',
    });
    assert.param('id')(() => typia.assert(id));
    assert.query(() => typia.assert(query));
    return random();
  };
}
