/**
 * @packageDocumentation
 * @module api.functional.auth.totp
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { TotpPayload } from '../../../structures/TotpPayload';
import type { IConnection } from '@nestia/fetcher';
import { PlainFetcher } from '@nestia/fetcher';
import type { Resolved } from 'typia';
import typia from 'typia';

/**
 * @controller AuthController.getTotpSecret
 * @path GET /auth/totp
 * @accessor api.functional.auth.totp.getTotpSecret
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getTotpSecret(
  connection: IConnection,
): Promise<getTotpSecret.Output> {
  return true === connection.simulate
    ? getTotpSecret.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getTotpSecret.METADATA,
        template: getTotpSecret.METADATA.path,
        path: getTotpSecret.path(),
      });
}
export namespace getTotpSecret {
  export type Output = null | TotpPayload;

  export const METADATA = {
    method: 'GET',
    path: '/auth/totp',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => '/auth/totp';
  export const random = (): Resolved<null | TotpPayload> =>
    typia.random<null | TotpPayload>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
