'use client';

import ContentButton from '@/app/components/common/ContentButton';
import AddNoteModal from '@/app/components/observations/notes/AddNoteModal';
import FormatNoteModal from '@/app/components/observations/notes/FormatNoteModal';
import NoteList, {
  type Note,
  type NoteAuditEntry,
} from '@/app/components/observations/notes/NoteList';
import dayjs from '@/app/utils/dayjs';
import { useMemo, useState, type JSX } from 'react';

/* -------------------------------------------------------------------------- */
/* Demo-only constants                                                        */
/* -------------------------------------------------------------------------- */

const DEMO_CURRENT_USER = 'Jane Smith';
const DEMO_CARD_CLASS_NAME =
  'flex items-start justify-between gap-6 rounded-3xl border border-rehua-maroon/20 bg-rehua-white/90 p-6';

/* -------------------------------------------------------------------------- */
/* Demo helper                                                                */
/* Creates initial demo notes.                                                */
/* In the real app, notes would be returned by the backend already containing */
/* both plainText and html.                                                   */
/* -------------------------------------------------------------------------- */

function createDemoNote(
  noteId: string,
  authorName: string,
  createdAt: string,
  plainText: string,
  html: string,
): Note {
  return {
    noteId,
    authorName,
    createdAt,
    plainText,
    html,
  };
}

/* -------------------------------------------------------------------------- */
/* Demo-only initial data                                                     */
/* -------------------------------------------------------------------------- */

const INITIAL_NOTES: Note[] = [
  createDemoNote(
    'note-1',
    'Jane Smith',
    '2026-08-01T12:15:00.000Z',
    'This is a test note.\n\n\nIt has multiple lines.',
    '<p>This is a test note.</p><p>&nbsp;</p><p>&nbsp;</p><p>It has multiple lines.</p>',
  ),
  createDemoNote(
    'note-2',
    'Jane Smith',
    '2026-08-01T12:30:00.000Z',
    'These notes are not changable.\nNurse running notes are preserved.',
    '<p>These notes are not changable.</p><p>Nurse running notes are preserved.</p>',
  ),
  createDemoNote(
    'note-3',
    'John Doe',
    '2026-08-01T15:15:00.000Z',
    'A note with <escaped> characters & a second line.',
    '<p>A note with &lt;escaped&gt; characters &amp; on one line.</p>',
  ),
];

function RunningNotes(): JSX.Element {
  /* ------------------------------------------------------------------------ */
  /* FRONTEND STATE                                                           */
  /* The screen owns the current list of notes and which modal is open.       */
  /* ------------------------------------------------------------------------ */

  const [notes, setNotes] = useState<Note[]>(() => INITIAL_NOTES);

  const [isAddNoteOpen, setIsAddNoteOpen] = useState(false);

  const [editingNoteId, setEditingNoteId] = useState<string | null>(null);

  const editingNote = useMemo(
    () => notes.find((note) => note.noteId === editingNoteId) ?? null,
    [notes, editingNoteId],
  );

  /* ------------------------------------------------------------------------ */
  /* FRONTEND: create note                                                    */
  /* AddNoteModal already converts plain text -> HTML internally.             */
  /* The parent receives BOTH values and only adds metadata.                  */
  /* ------------------------------------------------------------------------ */

  function handleAddNote(noteInput: { plainText: string; html: string }): void {
    const createdAt = dayjs().toISOString();

    const newNote: Note = {
      noteId: 'note-' + String(Date.now()), // using date object as this is an example/demo id

      // In the real app, this would come from the authenticated user.
      authorName: DEMO_CURRENT_USER,

      createdAt,

      // Immutable source text.
      plainText: noteInput.plainText,

      // Initial formatted representation generated by AddNoteModal.
      html: noteInput.html,
    };

    setNotes((currentNotes) => [newNote, ...currentNotes]);

    /* ---------------------------------------------------------------------- */
    /* DEMO ONLY: show what the frontend would send/store                     */
    /* ---------------------------------------------------------------------- */

    console.group('Create note');
    console.log('plainText', newNote.plainText);
    console.log('html', newNote.html);
    console.groupEnd();

    setIsAddNoteOpen(false);
  }

  /* ------------------------------------------------------------------------ */
  /* FRONTEND: save formatting                                                */
  /* FormatNoteModal returns the updated HTML and audit metadata.             */
  /* The screen updates local state so the UI changes immediately.            */
  /* ------------------------------------------------------------------------ */

  function handleSaveFormatting(auditUpdate: {
    noteId: string;
    formattedBy: string;
    formattedAt: string;
    beforeHtml: string;
    afterHtml: string;
  }): void {
    setNotes((currentNotes) =>
      currentNotes.map((note) => {
        if (note.noteId !== auditUpdate.noteId) {
          return note;
        }

        /* ------------------------------------------------------------------ */
        /* DEMO: keep audit history locally so the button becomes visible.    */
        /* In the real app, the backend would generate auditId and persist it.*/
        /* ------------------------------------------------------------------ */

        const auditEntry: NoteAuditEntry = {
          auditId: 'audit-' + String(Date.now()),
          formattedBy: auditUpdate.formattedBy,
          formattedAt: auditUpdate.formattedAt,
          beforeHtml: auditUpdate.beforeHtml,
          afterHtml: auditUpdate.afterHtml,
        };

        return {
          ...note,

          // Update the formatted representation shown in the list.
          html: auditUpdate.afterHtml,

          // Latest formatting summary.
          lastFormattedBy: auditUpdate.formattedBy,
          lastFormattedAt: auditUpdate.formattedAt,

          // Demo-only local audit accumulation.
          auditHistory: [...(note.auditHistory ?? []), auditEntry],
        };
      }),
    );

    /* ---------------------------------------------------------------------- */
    /* DEMO ONLY: inspect formatting changes                                  */
    /* ---------------------------------------------------------------------- */

    console.group('Format note');
    console.log('beforeHtml', auditUpdate.beforeHtml);
    console.log('afterHtml', auditUpdate.afterHtml);
    console.groupEnd();

    setEditingNoteId(null);
  }

  /* ------------------------------------------------------------------------ */
  /* REAL BACKEND RESPONSIBILITY (not implemented in this demo)               */
  /* ------------------------------------------------------------------------ */

  /*
  On CREATE:
  - generate noteId (or database id)
  - store plainText
  - store html
  - store authorName
  - store createdAt

  On FORMAT SAVE:
  - load note by noteId
  - verify stripHtml(afterHtml) === stored plainText
  - update html
  - update lastFormattedBy / lastFormattedAt
  - create NoteAuditEntry with generated auditId
  - append auditHistory
  */

  return (
    <>
      <section className="mx-auto flex max-w-5xl flex-col gap-6 px-6 py-8">
        <div
          className={DEMO_CARD_CLASS_NAME}
          style={{ boxShadow: '0 12px 40px rgba(0,0,0,0.08)' }}
        >
          <div className="flex items-start gap-4">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold text-rehua-maroon">
                Running Notes Demonstration
              </h2>
            </div>
          </div>

          <ContentButton
            text1="New Note"
            iconProps={{ name: 'plus' }}
            backgroundColor="bg-rehua-green"
            textIconGap={0.3}
            verticalPadding={0.2}
            onClick={() => {
              setIsAddNoteOpen(true);
            }}
          />
        </div>

        <NoteList
          notes={notes}
          onEditFormatting={(note) => {
            setEditingNoteId(note.noteId);
          }}
          onViewAuditHistory={() => {
            // Demo intentionally does nothing here.
            // The button still appears because auditHistory is populated.
          }}
        />
      </section>

      <AddNoteModal
        open={isAddNoteOpen}
        onClose={() => {
          setIsAddNoteOpen(false);
        }}
        onAdd={handleAddNote}
      />

      {editingNote ? (
        <FormatNoteModal
          open={true}
          currentUser={DEMO_CURRENT_USER}
          note={editingNote}
          onClose={() => {
            setEditingNoteId(null);
          }}
          onSave={handleSaveFormatting}
        />
      ) : null}
    </>
  );
}

export default RunningNotes;
