import { DocumentsService } from './documents.service';
import {
  CreateFileDocumentDto,
  CreateFormDocumentDto,
} from './dto/create-document.dto';
import { FindDocumentDto } from './dto/find-document.dto';
import { UpdateFormDocumentDto } from './dto/update-document.dto';
import { getFilesFromRequest } from '@/utils/helpers';
import type { MongoId } from '@/utils/types';
import { TypedBody, TypedFormData, TypedParam, TypedRoute } from '@nestia/core';
import {
  BadRequestException,
  Controller,
  Get,
  Param,
  Req,
  StreamableFile,
} from '@nestjs/common';
import type { Request } from 'express';
import { remove } from 'fs-extra';
import { UpdateWriteOpResult } from 'mongoose';

@Controller('documents')
export class DocumentsController {
  constructor(private readonly documentsService: DocumentsService) {}

  @TypedRoute.Post('file')
  async createFile(
    @Req() request: Request,
    @TypedFormData.Body(DocumentsService.getMulter)
    createFileDocumentDto: CreateFileDocumentDto,
  ): Promise<{ _id: MongoId }> {
    const files = getFilesFromRequest(request);

    try {
      // Check if exactly one file is uploaded
      if (files.length !== 1 || files[0] === undefined) {
        throw new BadRequestException('Exactly one file must be uploaded.');
      }

      // Store the uploaded file using the ManualService
      return await this.documentsService.createFile(
        createFileDocumentDto,
        files[0],
      );
    } finally {
      // Remove the temporary files after proc essing to avoid cluttering the server's storage.
      // SAFETY: these files are temporary files generated by Multer.
      await Promise.all(files.map(async (file) => remove(file.path)));
    }
  }

  @TypedRoute.Post('form')
  async createForm(
    @TypedBody()
    createFormDocumentDto: CreateFormDocumentDto,
  ): Promise<{
    _id: MongoId;
    patientId: MongoId;
    templateId: MongoId;
    data: Record<string, unknown>;
  }> {
    const doc = await this.documentsService.createForm(createFormDocumentDto);

    return {
      _id: doc._id.toString(),
      patientId: doc.patientId.toString(),
      templateId: doc.templateId.toString(),
      data: doc.data,
    };
  }

  @TypedRoute.Post('form/:id')
  async updateForm(
    @TypedParam('id') id: MongoId,
    @TypedBody()
    updateFormDocumentDto: UpdateFormDocumentDto,
  ): Promise<UpdateWriteOpResult> {
    return this.documentsService.updateForm(id, updateFormDocumentDto);
  }

  @TypedRoute.Get(':id')
  async findOne(
    @TypedParam('id') id: MongoId,
  ): Promise<FindDocumentDto | null> {
    const doc = await this.documentsService.findOne(id);
    if (!doc) {
      return null;
    }

    const patientId = doc.patientId.toString();

    if ('path' in doc) {
      return new FindDocumentDto(patientId, doc.tags);
    }

    const { __v, _id, ...template } = doc.templateId.toJSON();
    return new FindDocumentDto(
      patientId,
      doc.tags,
      template,
      doc.toJSON().data,
    );
  }

  /**
   * @ignore
   * @description This endpoint is used to view the file type document and the SDK does not support it.
   */
  @Get('file/:id')
  async getFile(@Param('id') id: string): Promise<StreamableFile> {
    return this.documentsService.getFile(id);
  }
}
