import { DocumentsService } from './documents.service';
import {
  CreateFileDocumentDto,
  CreateFormDocumentDto,
} from './dto/create-document.dto';
import { FindDocumentDto } from './dto/find-document.dto';
import { FormDocument } from './entities/document.entity';
import { getFilesFromRequest } from '@/utils/helpers';
import type { MongoId } from '@/utils/types';
import { TypedBody, TypedFormData, TypedParam, TypedRoute } from '@nestia/core';
import {
  BadRequestException,
  Controller,
  Req,
  StreamableFile,
} from '@nestjs/common';
import type { Request } from 'express';
import { remove } from 'fs-extra';

@Controller('documents')
export class DocumentsController {
  constructor(private readonly documentsService: DocumentsService) {}

  @TypedRoute.Post('file')
  async createFile(
    @Req() request: Request,
    @TypedFormData.Body(DocumentsService.getMulter)
    createFileDocumentDto: CreateFileDocumentDto,
  ): Promise<{ _id: MongoId }> {
    const files = getFilesFromRequest(request);

    try {
      // Check if exactly one file is uploaded
      if (files.length !== 1 || files[0] === undefined) {
        throw new BadRequestException('Exactly one file must be uploaded.');
      }

      // Store the uploaded file using the ManualService
      return await this.documentsService.createFile(
        createFileDocumentDto,
        files[0],
      );
    } finally {
      // Remove the temporary files after proc essing to avoid cluttering the server's storage.
      // SAFETY: these files are temporary files generated by Multer.
      await Promise.all(files.map(async (file) => remove(file.path)));
    }
  }

  @TypedRoute.Post('form')
  async createForm(
    @TypedBody()
    createFormDocumentDto: CreateFormDocumentDto,
  ): Promise<FormDocument & { _id: MongoId }> {
    const doc = await this.documentsService.createForm(createFormDocumentDto);

    return {
      // eslint-disable-next-line @typescript-eslint/no-misused-spread
      ...doc.toJSON(),
      _id: doc._id.toString(),
    };
  }

  @TypedRoute.Get(':id')
  async findOne(
    @TypedParam('id') id: MongoId,
  ): Promise<FindDocumentDto | null> {
    const doc = await this.documentsService.findOne(id);
    if (!doc) {
      return null;
    }

    const patientId = doc.patientId.toString();

    if ('path' in doc) {
      return new FindDocumentDto(patientId);
    }

    const { __v, _id, ...template } = doc.templateId.toJSON();
    return new FindDocumentDto(patientId, template, doc.data);
  }

  /**
   * @ignore
   * @description This endpoint is used to view the file type document and the SDK does not support it.
   */
  @TypedRoute.Get('file/:id')
  async getFile(@TypedParam('id') id: string): Promise<StreamableFile> {
    return this.documentsService.getFile(id);
  }
}
