import {
  CreateFileDocumentDto,
  CreateFormDocumentDto,
} from './dto/create-document.dto';
import {
  FileDocument,
  FileDocumentDocument,
  FormDocument,
  FormDocumentDocument,
  FormDocumentPopulatedDocument,
} from './entities/document.entity';
import { PatientService } from '@/schema/patients/patient.service';
import { TemplateDocument } from '@/templates/entities/template.entity';
import { Config } from '@/utils/config';
import dayjs from '@/utils/dayjs';
import { MongoId } from '@/utils/types';
import {
  BadRequestException,
  Injectable,
  NotFoundException,
  StreamableFile,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { InjectModel } from '@nestjs/mongoose';
import { access, constants, createReadStream, move } from 'fs-extra';
import { Model } from 'mongoose';
import multer, { diskStorage, Multer } from 'multer';
import { join } from 'node:path';
import typia from 'typia';

@Injectable()
export class DocumentsService {
  private static multerInstance?: Multer;
  public _filePath: string;

  constructor(
    private readonly configService: ConfigService<Config, true>,
    @InjectModel(FileDocument.name)
    private readonly fileDocumentModel: Model<FileDocument>,
    @InjectModel(FormDocument.name)
    private readonly formDocumentModel: Model<FormDocument>,
    private readonly patientService: PatientService,
  ) {
    this._filePath = this.configService.getOrThrow('DATA_PATH');

    // Initialize the Multer instance for handling file uploads if it hasn't been initialized yet.
    DocumentsService.multerInstance ??= multer({
      storage: diskStorage({ destination: this._filePath }),

      limits: { fileSize: this.configService.getOrThrow('MAX_FILE_SIZE') },
    });
  }

  // This static method returns the static Multer instance for handling file uploads.
  static getMulter(): multer.Multer {
    if (!DocumentsService.multerInstance) {
      throw new Error('Multer instance is not initialized.');
    }

    return DocumentsService.multerInstance;
  }

  async createFile(
    createFileDocumentDto: CreateFileDocumentDto,
    file: Express.Multer.File,
  ): Promise<{ _id: MongoId }> {
    const patient = await this.patientService.findOne(
      createFileDocumentDto.patientId,
    );
    if (!patient) {
      throw new BadRequestException(
        `Patient with ID ${createFileDocumentDto.patientId} not found.`,
      );
    }

    const patientName = `${patient.firstName}_${patient.lastName}`.replace(
      /\s+/g,
      '_',
    );

    const filePath = join(
      this._filePath,
      `${patientName}_${dayjs().toISOString()}_${file.originalname}`,
    );

    // SAFETY: this file is a temporary file generated by Multer.
    await move(file.path, filePath);

    const doc = await this.fileDocumentModel.create({
      patientId: createFileDocumentDto.patientId,
      path: filePath,
      fileName: file.originalname,
    });
    return { _id: doc._id.toString() };
  }

  async createForm(
    createFormDocumentDto: CreateFormDocumentDto,
  ): Promise<FormDocumentDocument> {
    return this.formDocumentModel.create(createFormDocumentDto);
  }

  async findOne(
    id: MongoId,
  ): Promise<
    | FormDocumentPopulatedDocument<{ templateId: TemplateDocument }>
    | FileDocumentDocument
    | null
  > {
    const formDocument = await this.formDocumentModel
      .findById(id)
      .populate<{ templateId: TemplateDocument }>('templateId')
      .exec();
    if (formDocument?.populated('templateId')) {
      console.log('Form Document:', formDocument.toJSON());
      return formDocument;
    }

    const fileDocument = await this.fileDocumentModel.findById(id).exec();
    if (fileDocument) {
      console.log('File Document:', fileDocument.toJSON());
      return fileDocument;
    }

    return null;
  }

  async getFile(id: MongoId): Promise<StreamableFile> {
    const fileDocument = await this.fileDocumentModel
      .findById(id)
      .orFail()
      .exec();
    const filePath = fileDocument.path;

    try {
      await access(filePath, constants.R_OK);
    } catch (e: unknown) {
      typia.assertGuard<NodeJS.ErrnoException>(e);
      throw new NotFoundException('File not found', e);
    }

    const file = createReadStream(filePath);
    return new StreamableFile(file, {
      disposition: `inline; filename="${fileDocument.fileName}"`,
    });
  }
}
