/**
 * @packageDocumentation
 * @module api.functional.documents.tag
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import type { Resolved, tags } from 'typia';
import typia from 'typia';

/**
 * @controller DocumentsController.updateTags
 * @path PATCH /documents/tag/:id
 * @accessor api.functional.documents.tag.updateTags
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateTags(
  connection: IConnection,
  id: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>,
  tags: updateTags.Body,
): Promise<void> {
  typia.assert<typeof id>(id);
  typia.assert<typeof tags>(tags);
  return true === connection.simulate
    ? updateTags.simulate(connection, id, tags)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            'Content-Type': 'application/json',
          },
        },
        {
          ...updateTags.METADATA,
          template: updateTags.METADATA.path,
          path: updateTags.path(id),
        },
        tags,
      );
}
export namespace updateTags {
  export type Body = string[];

  export const METADATA = {
    method: 'PATCH',
    path: '/documents/tag/:id',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>) =>
    `/documents/tag/${encodeURIComponent(id?.toString() ?? 'null')}`;
  export const random = (): Resolved<void> => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    id: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>,
    tags: Body,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: 'application/json',
    });
    assert.param('id')(() => typia.assert(id));
    assert.body(() => typia.assert(tags));
    return random();
  };
}
