/**
 * @packageDocumentation
 * @module api.functional.auth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { ExpressUser } from '../../structures/ExpressUser';
import type { LoginBody } from '../../structures/LoginBody';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import type { Resolved } from 'typia';
import typia from 'typia';

export * as totp from './totp/index';

/**
 * @controller AuthController.login
 * @path POST /auth/login
 * @accessor api.functional.auth.login
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function login(
  connection: IConnection,
  _body: login.Body,
): Promise<login.Output> {
  return true === connection.simulate
    ? login.simulate(connection, _body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            'Content-Type': 'application/json',
          },
        },
        {
          ...login.METADATA,
          template: login.METADATA.path,
          path: login.path(),
        },
        _body,
      );
}
export namespace login {
  export type Body = LoginBody;
  export type Output = ExpressUser;

  export const METADATA = {
    method: 'POST',
    path: '/auth/login',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => '/auth/login';
  export const random = (): Resolved<ExpressUser> =>
    typia.random<ExpressUser>();
  export const simulate = (connection: IConnection, _body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: 'application/json',
    });
    assert.body(() => typia.assert(_body));
    return random();
  };
}
