/**
 * @packageDocumentation
 * @module api.functional.auth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { LoginBody } from '../../structures/LoginBody';
import type { LoginResponseDto } from '../../structures/LoginResponseDto';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import type { Resolved } from 'typia';
import typia from 'typia';

export * as totp from './totp/index';

/**
 * @controller AuthController.login
 * @path POST /auth/login
 * @accessor api.functional.auth.login
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function login(
  connection: IConnection,
  _body: login.Body,
): Promise<login.Output> {
  return true === connection.simulate
    ? login.simulate(connection, _body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            'Content-Type': 'application/json',
          },
        },
        {
          ...login.METADATA,
          template: login.METADATA.path,
          path: login.path(),
        },
        _body,
      );
}
export namespace login {
  export type Body = LoginBody;
  export type Output = LoginResponseDto;

  export const METADATA = {
    method: 'POST',
    path: '/auth/login',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => '/auth/login';
  export const random = (): Resolved<LoginResponseDto> =>
    typia.random<LoginResponseDto>();
  export const simulate = (connection: IConnection, _body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: 'application/json',
    });
    assert.body(() => typia.assert(_body));
    return random();
  };
}

/**
 * @controller AuthController.refresh
 * @path POST /auth/refresh
 * @accessor api.functional.auth.refresh
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function refresh(
  connection: IConnection,
): Promise<refresh.Output> {
  return true === connection.simulate
    ? refresh.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...refresh.METADATA,
        template: refresh.METADATA.path,
        path: refresh.path(),
      });
}
export namespace refresh {
  export type Output = {
    success: boolean;
  };

  export const METADATA = {
    method: 'POST',
    path: '/auth/refresh',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => '/auth/refresh';
  export const random = (): Resolved<{
    success: boolean;
  }> =>
    typia.random<{
      success: boolean;
    }>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}

/**
 * @controller AuthController.logout
 * @path POST /auth/logout
 * @accessor api.functional.auth.logout
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function logout(connection: IConnection): Promise<logout.Output> {
  return true === connection.simulate
    ? logout.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...logout.METADATA,
        template: logout.METADATA.path,
        path: logout.path(),
      });
}
export namespace logout {
  export type Output = {
    success: boolean;
  };

  export const METADATA = {
    method: 'POST',
    path: '/auth/logout',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => '/auth/logout';
  export const random = (): Resolved<{
    success: boolean;
  }> =>
    typia.random<{
      success: boolean;
    }>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
