/**
 * @packageDocumentation
 * @module api.functional.templates.page
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { PaginatedResponseDtoTemplate_idMongoId } from '../../../structures/PaginatedResponseDtoTemplate_idMongoId';
import type { PaginationQueryDto } from '../../../structures/PaginationQueryDto';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import typia from 'typia';
import type { Resolved } from 'typia';

/**
 * @controller TemplatesController.findPage
 * @path GET /templates/page/:pageNumber/:numberOfRows
 * @accessor api.functional.templates.page.findPage
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findPage(
  connection: IConnection,
  numberOfRows: number,
  pageNumber: number,
  query: findPage.Query,
): Promise<findPage.Output> {
  typia.assert<typeof numberOfRows>(numberOfRows);
  typia.assert<typeof pageNumber>(pageNumber);
  typia.assert<typeof query>(query);
  return true === connection.simulate
    ? findPage.simulate(connection, numberOfRows, pageNumber, query)
    : PlainFetcher.fetch(connection, {
        ...findPage.METADATA,
        template: findPage.METADATA.path,
        path: findPage.path(numberOfRows, pageNumber, query),
      });
}
export namespace findPage {
  export type Query = PaginationQueryDto;
  export type Output = PaginatedResponseDtoTemplate_idMongoId;

  export const METADATA = {
    method: 'GET',
    path: '/templates/page/:pageNumber/:numberOfRows',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    numberOfRows: number,
    pageNumber: number,
    query: Query,
  ) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/templates/page/${encodeURIComponent(pageNumber?.toString() ?? 'null')}/${encodeURIComponent(numberOfRows?.toString() ?? 'null')}`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): Resolved<PaginatedResponseDtoTemplate_idMongoId> =>
    typia.random<PaginatedResponseDtoTemplate_idMongoId>();
  export const simulate = (
    connection: IConnection,
    numberOfRows: number,
    pageNumber: number,
    query: Query,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(numberOfRows, pageNumber, query),
      contentType: 'application/json',
    });
    assert.param('numberOfRows')(() => typia.assert(numberOfRows));
    assert.param('pageNumber')(() => typia.assert(pageNumber));
    assert.query(() => typia.assert(query));
    return random();
  };
}
