/**
 * @packageDocumentation
 * @module api.functional.hello
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { CreateHelloDto } from '../../structures/CreateHelloDto';
import type { DeleteResult } from '../../structures/DeleteResult';
import type { Hello } from '../../structures/Hello';
import type { Hello_idstring } from '../../structures/Hello_idstring';
import type { UpdateHelloDto } from '../../structures/UpdateHelloDto';
import type { mongoose } from '../../structures/mongoose';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import type { Resolved } from 'typia';
import typia from 'typia';

/**
 * @controller HelloController.create
 * @path POST /hello
 * @accessor api.functional.hello.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  createHelloDto: create.Body,
): Promise<create.Output> {
  return true === connection.simulate
    ? create.simulate(connection, createHelloDto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            'Content-Type': 'application/json',
          },
        },
        {
          ...create.METADATA,
          template: create.METADATA.path,
          path: create.path(),
        },
        createHelloDto,
      );
}
export namespace create {
  export type Body = CreateHelloDto;
  export type Output = Hello_idstring;

  export const METADATA = {
    method: 'POST',
    path: '/hello',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => '/hello';
  export const random = (): Resolved<Hello_idstring> =>
    typia.random<Hello_idstring>();
  export const simulate = (
    connection: IConnection,
    createHelloDto: Body,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: 'application/json',
    });
    assert.body(() => typia.assert(createHelloDto));
    return random();
  };
}

/**
 * @controller HelloController.findAll
 * @path GET /hello
 * @accessor api.functional.hello.findAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
): Promise<findAll.Output> {
  return true === connection.simulate
    ? findAll.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...findAll.METADATA,
        template: findAll.METADATA.path,
        path: findAll.path(),
      });
}
export namespace findAll {
  export type Output = Hello[];

  export const METADATA = {
    method: 'GET',
    path: '/hello',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => '/hello';
  export const random = (): Resolved<Hello[]> => typia.random<Hello[]>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}

/**
 * @controller HelloController.findOne
 * @path GET /hello/:id
 * @accessor api.functional.hello.findOne
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findOne(
  connection: IConnection,
  id: string,
): Promise<findOne.Output> {
  return true === connection.simulate
    ? findOne.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...findOne.METADATA,
        template: findOne.METADATA.path,
        path: findOne.path(id),
      });
}
export namespace findOne {
  export type Output = null | Hello;

  export const METADATA = {
    method: 'GET',
    path: '/hello/:id',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/hello/${encodeURIComponent(id?.toString() ?? 'null')}`;
  export const random = (): Resolved<null | Hello> =>
    typia.random<null | Hello>();
  export const simulate = (connection: IConnection, id: string): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: 'application/json',
    });
    assert.param('id')(() => typia.assert(id));
    return random();
  };
}

/**
 * @controller HelloController.update
 * @path PATCH /hello/:id
 * @accessor api.functional.hello.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  updateHelloDto: update.Body,
): Promise<update.Output> {
  return true === connection.simulate
    ? update.simulate(connection, id, updateHelloDto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            'Content-Type': 'application/json',
          },
        },
        {
          ...update.METADATA,
          template: update.METADATA.path,
          path: update.path(id),
        },
        updateHelloDto,
      );
}
export namespace update {
  export type Body = UpdateHelloDto;
  export type Output = mongoose.UpdateWriteOpResult;

  export const METADATA = {
    method: 'PATCH',
    path: '/hello/:id',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/hello/${encodeURIComponent(id?.toString() ?? 'null')}`;
  export const random = (): Resolved<mongoose.UpdateWriteOpResult> =>
    typia.random<mongoose.UpdateWriteOpResult>();
  export const simulate = (
    connection: IConnection,
    id: string,
    updateHelloDto: Body,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: 'application/json',
    });
    assert.param('id')(() => typia.assert(id));
    assert.body(() => typia.assert(updateHelloDto));
    return random();
  };
}

/**
 * @controller HelloController.remove
 * @path DELETE /hello/:id
 * @accessor api.functional.hello.remove
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function remove(
  connection: IConnection,
  id: string,
): Promise<remove.Output> {
  return true === connection.simulate
    ? remove.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...remove.METADATA,
        template: remove.METADATA.path,
        path: remove.path(id),
      });
}
export namespace remove {
  export type Output = DeleteResult;

  export const METADATA = {
    method: 'DELETE',
    path: '/hello/:id',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/hello/${encodeURIComponent(id?.toString() ?? 'null')}`;
  export const random = (): Resolved<DeleteResult> =>
    typia.random<DeleteResult>();
  export const simulate = (connection: IConnection, id: string): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: 'application/json',
    });
    assert.param('id')(() => typia.assert(id));
    return random();
  };
}
