/**
 * @packageDocumentation
 * @module api.functional.documents.patient
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { FindDocumentByPatientDto } from '../../../structures/FindDocumentByPatientDto';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import type { Resolved, tags } from 'typia';
import typia from 'typia';

/**
 * @controller DocumentsController.findByPatient
 * @path GET /documents/patient/:patientId
 * @accessor api.functional.documents.patient.findByPatient
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findByPatient(
  connection: IConnection,
  patientId: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>,
): Promise<findByPatient.Output> {
  typia.assert<typeof patientId>(patientId);
  return true === connection.simulate
    ? findByPatient.simulate(connection, patientId)
    : PlainFetcher.fetch(connection, {
        ...findByPatient.METADATA,
        template: findByPatient.METADATA.path,
        path: findByPatient.path(patientId),
      });
}
export namespace findByPatient {
  export type Output = FindDocumentByPatientDto[];

  export const METADATA = {
    method: 'GET',
    path: '/documents/patient/:patientId',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (patientId: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>) =>
    `/documents/patient/${encodeURIComponent(patientId?.toString() ?? 'null')}`;
  export const random = (): Resolved<FindDocumentByPatientDto[]> =>
    typia.random<FindDocumentByPatientDto[]>();
  export const simulate = (
    connection: IConnection,
    patientId: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(patientId),
      contentType: 'application/json',
    });
    assert.param('patientId')(() => typia.assert(patientId));
    return random();
  };
}
