export enum ObservationType {
  //Numrical Observations
  OXYGEN_RATE = 'OXYGEN_RATE',
  RESPIRATION_RATE = 'RESPIRATION_RATE',
  BLOOD_PRESSURE = 'BLOOD_PRESSURE',
  HEART_RATE = 'HEART_RATE',
  TEMPERATURE = 'TEMPERATURE',
  WEIGHT = 'WEIGHT',
  BLOOD_GLUCOSE_LEVELS = 'BLOOD_GLUCOSE_LEVELS',
  NEUROLOGICAL_OBSERVATION_CHART = 'NEUROLOGICAL_OBSERVATION_CHART',

  //Test and Notes based Observations
  BOWEL_OUTPUT = 'BOWEL_OUTPUT',
  URINE_OUTPUT = 'URINE_OUTPUT',
}
