/**
 * @packageDocumentation
 * @module api.functional.manual
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { CreateManualDto } from '../../structures/CreateManualDto';
import type { FormDataInput, IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import type { Resolved } from 'typia';
import typia from 'typia';

/**
 * @description This endpoint is used to upload a new PDF manual.
 * @controller ManualController.create
 * @path POST /manual
 * @accessor api.functional.manual.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  _: create.Body,
): Promise<create.Output> {
  return true === connection.simulate
    ? create.simulate(connection, _)
    : PlainFetcher.fetch(
        connection,
        {
          ...create.METADATA,
          template: create.METADATA.path,
          path: create.path(),
        },
        _,
      );
}
export namespace create {
  export type Body = FormDataInput<CreateManualDto>;
  export type Output = true;

  export const METADATA = {
    method: 'POST',
    path: '/manual',
    request: {
      type: 'multipart/form-data',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => '/manual';
  export const random = (): Resolved<true> => typia.random<true>();
  export const simulate = (connection: IConnection, _: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: 'application/json',
    });
    assert.body(() => typia.assert(_));
    return random();
  };
}
