import * as paginationRequestDto from '../patients/dto/pagination-request.dto';
import { CurrentUser } from '../users/users.decorator';
import type { CreatePatientDto } from './dto/create-patient.dto';
import { PaginatedResponseDto } from './dto/pagination-response.dto';
import { UpdatePatientDto } from './dto/update-patient.dto';
import { Patient } from './entities/patient.entity';
import { PatientService } from './patient.service';
import { Roles } from '@/auth/roles.decorator';
import { getFilesFromRequest } from '@/utils/helpers';
import {
  SwaggerExample,
  TypedFormData,
  TypedParam,
  TypedQuery,
  TypedRoute,
} from '@nestia/core';
import {
  BadRequestException,
  Controller,
  Get,
  Param,
  Req,
  StreamableFile,
} from '@nestjs/common';
import type { Request } from 'express';
import { remove } from 'fs-extra';
import { UpdateWriteOpResult } from 'mongoose';

@Roles('admin', 'nurse')
@Controller('patient')
export class PatientController {
  constructor(private readonly patientService: PatientService) {}

  @TypedRoute.Post()
  async create(
    @Req() request: Request,
    @TypedFormData.Body(PatientService.getMulter)
    createPatientDto: CreatePatientDto,
  ): Promise<Patient & { _id: string }> {
    const files = getFilesFromRequest(request);

    try {
      // Check if exactly zero or one file is uploaded
      if (files.length > 1) {
        throw new BadRequestException(
          'Exactly zero or one file must be uploaded.',
        );
      }

      const doc = await this.patientService.create({
        // eslint-disable-next-line @typescript-eslint/no-misused-spread
        ...createPatientDto,
        profilePicture: files[0],
      });

      return {
        // eslint-disable-next-line @typescript-eslint/no-misused-spread
        ...doc.toJSON(),
        _id: doc._id.toString(),
      };
    } finally {
      // Remove the temporary files after proc essing to avoid cluttering the server's storage.
      // SAFETY: these files are temporary files generated by Multer.
      await Promise.all(files.map(async (file) => remove(file.path)));
    }
  }

  /**
   * @ignore
   * @description This endpoint is used to view the profile picture and the SDK does not support it.
   */
  @Get('picture/:id')
  async getProfilePicture(@Param('id') id: string): Promise<StreamableFile> {
    return this.patientService.getProfilePicture(id);
  }

  @TypedRoute.Get()
  async findAll(): Promise<(Patient & { _id: string })[]> {
    const docs = await this.patientService.findAll();

    return docs.map((doc) => ({
      // eslint-disable-next-line @typescript-eslint/no-misused-spread
      ...doc.toJSON(),
      _id: doc._id.toString(),
    }));
  }

  @SwaggerExample.Response('Found', {
    value: new Patient(
      'John',
      'Doe',
      '1990-07-21',
      '123 street, city, suburb',
      '1234567',
      '2026-06-20',
      'David at Main Hospital',
      'Sarah Smith',
      'longTerm',
      'email@domain.com',
      '+64 123 456789',
      'Male',
      'English',
      'Married',
      'Kiwi',
      'Nuts',
    ),
  })
  @SwaggerExample.Response('Not found', { value: null })
  @TypedRoute.Get(':id')
  async findOne(
    @TypedParam('id') id: string,
  ): Promise<(Patient & { _id: string }) | null> {
    const doc = await this.patientService.findOne(id);

    const formattedDoc = doc
      ? {
          // eslint-disable-next-line @typescript-eslint/no-misused-spread
          ...doc.toJSON(),
          _id: doc._id.toString(),
        }
      : null;

    return formattedDoc;
  }

  //returns patients like in a the list view (number of results shown, page number)
  //optional filters
  @TypedRoute.Get('page/:pageNumber/:numberOfRows')
  async findPage(
    @CurrentUser() user: { group: string },
    @TypedParam('numberOfRows') numberOfRows: number,
    @TypedParam('pageNumber') pageNumber: number,
    @TypedQuery() query: paginationRequestDto.PaginationQueryDto,
  ): Promise<PaginatedResponseDto<Patient & { _id: string }>> {
    const { filter, search } = query;

    let paginatedResult;

    if (filter || search) {
      paginatedResult = await this.patientService.findPageByFilter(
        numberOfRows,
        pageNumber,
        filter ?? '',
        search ?? '',
        user.group,
      );
    } else {
      paginatedResult = await this.patientService.findPage(
        numberOfRows,
        pageNumber,
        user.group,
      );
    }

    const formattedDocs = paginatedResult.data.map((doc) => ({
      // eslint-disable-next-line @typescript-eslint/no-misused-spread
      ...doc.toJSON(),
      _id: doc._id.toString(),
    }));

    return {
      data: formattedDocs,
      meta: paginatedResult.meta,
    };
  }

  @TypedRoute.Patch(':id')
  async update(
    @Req() request: Request,
    @TypedParam('id') id: string,
    @TypedFormData.Body(PatientService.getMulter)
    updatePatientDto: UpdatePatientDto,
  ): Promise<UpdateWriteOpResult> {
    const files = getFilesFromRequest(request);

    try {
      // Check if exactly zero or one file is uploaded
      if (files.length > 1) {
        throw new BadRequestException(
          'Exactly zero or one file must be uploaded.',
        );
      }
      return await this.patientService.update(id, {
        // eslint-disable-next-line @typescript-eslint/no-misused-spread
        ...updatePatientDto,
        profilePicture: files[0],
      });
    } finally {
      // Remove the temporary files after proc essing to avoid cluttering the server's storage.
      // SAFETY: these files are temporary files generated by Multer.
      await Promise.all(files.map(async (file) => remove(file.path)));
    }
  }
}
