import type { CreatePatientDto } from './dto/create-patient.dto';
import { PaginatedResponseDto } from './dto/pagination-response.dto';
import { UpdatePatientDto } from './dto/update-patient.dto';
import { Patient, PatientDocument } from './entities/patient.entity';
import { Config } from '@/utils/config';
import {
  BadRequestException,
  Injectable,
  NotFoundException,
  StreamableFile,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { InjectModel } from '@nestjs/mongoose';
import { access, constants, createReadStream, move } from 'fs-extra';
import { lookup } from 'mime-types';
import {
  isObjectIdOrHexString,
  Model,
  QueryFilter,
  UpdateWriteOpResult,
} from 'mongoose';
import multer, { diskStorage, Multer } from 'multer';
import { extname, join } from 'node:path';
import type { SetFieldType } from 'type-fest';
import typia from 'typia';

@Injectable()
export class PatientService {
  private static multerInstance?: Multer;
  public _filePath: string;

  constructor(
    private readonly configService: ConfigService<Config, true>,
    @InjectModel(Patient.name) private readonly patientModel: Model<Patient>,
  ) {
    this._filePath = this.configService.getOrThrow('DATA_PATH');

    // Initialize the Multer instance for handling file uploads if it hasn't been initialized yet.
    PatientService.multerInstance ??= multer({
      storage: diskStorage({ destination: this._filePath }),

      limits: {
        fileSize: this.configService.getOrThrow('MAX_FILE_SIZE'),
      },
    });
  }

  // This static method returns the static Multer instance for handling file uploads.
  static getMulter(): multer.Multer {
    if (!PatientService.multerInstance) {
      throw new Error('Multer instance is not initialized.');
    }

    return PatientService.multerInstance;
  }

  async create(
    createPatientDto: SetFieldType<
      CreatePatientDto,
      'profilePicture',
      Express.Multer.File | undefined
    >,
  ): Promise<PatientDocument> {
    const { profilePicture, ...other } = createPatientDto;

    const createdPatient = new this.patientModel(other);
    // Ensure the _id has been created
    await createdPatient.save();

    createdPatient.profilePicture = await this.handleProfilePicture(
      createdPatient._id.toString(),
      profilePicture,
    );

    return createdPatient.save();
  }

  // TODO: remove old picture
  async handleProfilePicture(
    id: string,
    file: Express.Multer.File | undefined,
  ): Promise<string | undefined> {
    if (!file) {
      return undefined;
    }

    if (!isObjectIdOrHexString(id)) {
      throw new BadRequestException('Invalid patient ID');
    }

    const inferredType = lookup(file.originalname);
    if (
      !inferredType ||
      !inferredType.startsWith('image/') ||
      !file.mimetype.startsWith('image/') ||
      // Reject SVG
      inferredType.startsWith('image/svg') ||
      file.mimetype.startsWith('image/svg')
    ) {
      throw new BadRequestException(
        'Invalid file type. Only image files are allowed.',
      );
    }

    const fileName = `${id}${extname(file.originalname)}`;
    const filePath = join(this._filePath, 'profilePicture', fileName);

    // SAFETY: this file is a temporary file generated by Multer.
    await move(file.path, filePath, { overwrite: true });

    return fileName;
  }

  async getProfilePicture(id: string): Promise<StreamableFile> {
    const fileName = await this.patientModel
      .findById(id)
      .orFail(() => new NotFoundException('patient not found'))
      .select({ profilePicture: true })
      .lean()
      .transform((d) => d.profilePicture)
      .exec();
    if (!fileName) {
      throw new NotFoundException('File not found');
    }

    const filePath = join(this._filePath, 'profilePicture', fileName);

    try {
      await access(filePath, constants.R_OK);
    } catch (e: unknown) {
      typia.assertGuard<NodeJS.ErrnoException>(e);
      throw new NotFoundException('File not found', e);
    }

    const file = createReadStream(filePath);
    return new StreamableFile(file, {
      type: lookup(fileName) || 'application/octet-stream',
      disposition: `inline; filename="${fileName}"`,
    });
  }

  async findAll(): Promise<PatientDocument[]> {
    return this.patientModel.find().sort({ _id: 1 }).exec();
  }

  async findOne(id: string): Promise<PatientDocument | null> {
    return this.patientModel.findOne({ _id: id }).exec();
  }

  async findPage(
    numberOfRows: number,
    pageNumber: number,
    userGroup: string,
  ): Promise<PaginatedResponseDto<PatientDocument>> {
    const searchFilter: Record<string, unknown> = {};

    if (userGroup === 'nurse') {
      searchFilter['status'] = { $ne: 'deceased' };
    }

    const docs = await this.patientModel
      .find(searchFilter)
      .sort({ dateAdmitted: 'desc' })
      .skip((pageNumber - 1) * numberOfRows)
      .limit(numberOfRows)
      .exec();

    const totalDocuments = await this.patientModel.countDocuments();
    const totalPages = Math.ceil(totalDocuments / numberOfRows);

    return {
      data: docs,
      meta: {
        totalPages,
      },
    };
  }

  async findPageByFilter(
    numberOfRows: number,
    pageNumber: number,
    filter: string,
    search: string,
    userGroup: string,
  ): Promise<PaginatedResponseDto<PatientDocument>> {
    const searchFilter: Record<string, unknown> = {};

    if (userGroup === 'nurse') {
      searchFilter['status'] = { $ne: 'deceased' };
    }

    if (filter && search) {
      const escapedValue = search.replace(
        /[-[\]{}()*+?.,\\^$|#\s]/g,
        String.raw`\$&`,
      );

      searchFilter[filter] = {
        $regex: escapedValue,
        $options: 'i',
      };
    }

    const query = searchFilter as QueryFilter<PatientDocument>;

    interface PatientAggregateResult {
      data: PatientDocument[];
      total: number;
    }

    const [result] = await this.patientModel
      .aggregate<PatientAggregateResult>([
        { $match: query },
        {
          $facet: {
            totalCount: [{ $count: 'count' }],
            paginatedResults: [
              { $sort: { dateAdmitted: -1 } },
              { $skip: (pageNumber - 1) * numberOfRows },
              { $limit: numberOfRows },
            ],
          },
        },
        {
          $project: {
            data: '$paginatedResults',
            total: { $ifNull: [{ $arrayElemAt: ['$totalCount.count', 0] }, 0] },
          },
        },
      ])
      .exec();

    const rawData = result?.data ?? [];
    const total = result?.total ?? 0;

    // rehydrate the raw objects into full Mongoose documents, to allow contorller to add _id
    const data = rawData.map((doc) => this.patientModel.hydrate(doc));

    const totalFilteredDocuments = total;
    const totalPages = Math.ceil(totalFilteredDocuments / numberOfRows);

    return {
      data: data,
      meta: {
        totalPages,
      },
    };
  }

  async update(
    id: string,
    updatePatientDto: SetFieldType<
      UpdatePatientDto,
      'profilePicture',
      Express.Multer.File | undefined
    >,
  ): Promise<UpdateWriteOpResult> {
    if (!(await this.patientModel.exists({ _id: id }))) {
      throw new NotFoundException('Patient not found');
    }

    return this.patientModel
      .updateOne(
        { _id: id },
        {
          $set: {
            ...updatePatientDto,
            profilePicture: await this.handleProfilePicture(
              id,
              updatePatientDto.profilePicture,
            ),
          },
        },
      )
      .exec();
  }
}
