/**
 * @packageDocumentation
 * @module api.functional.patient
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { CreatePatientDto } from '../../structures/CreatePatientDto';
import type { Patient_idstring } from '../../structures/Patient_idstring';
import type { UpdatePatientDto } from '../../structures/UpdatePatientDto';
import type { mongoose } from '../../structures/mongoose';
import type { IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import typia from 'typia';
import type { Resolved } from 'typia';

export * as page from './page/index';

/**
 * @controller PatientController.create
 * @path POST /patient
 * @accessor api.functional.patient.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  createPatientDto: create.Body,
): Promise<create.Output> {
  typia.assert<typeof createPatientDto>(createPatientDto);
  return true === connection.simulate
    ? create.simulate(connection, createPatientDto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            'Content-Type': 'application/json',
          },
        },
        {
          ...create.METADATA,
          template: create.METADATA.path,
          path: create.path(),
        },
        createPatientDto,
      );
}
export namespace create {
  export type Body = CreatePatientDto;
  export type Output = Patient_idstring;

  export const METADATA = {
    method: 'POST',
    path: '/patient',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => '/patient';
  export const random = (): Resolved<Patient_idstring> =>
    typia.random<Patient_idstring>();
  export const simulate = (
    connection: IConnection,
    createPatientDto: Body,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: 'application/json',
    });
    assert.body(() => typia.assert(createPatientDto));
    return random();
  };
}

/**
 * @controller PatientController.findAll
 * @path GET /patient
 * @accessor api.functional.patient.findAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
): Promise<findAll.Output> {
  return true === connection.simulate
    ? findAll.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...findAll.METADATA,
        template: findAll.METADATA.path,
        path: findAll.path(),
      });
}
export namespace findAll {
  export type Output = Patient_idstring.o1[];

  export const METADATA = {
    method: 'GET',
    path: '/patient',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => '/patient';
  export const random = (): Resolved<Patient_idstring.o1[]> =>
    typia.random<Patient_idstring.o1[]>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}

/**
 * @controller PatientController.findOne
 * @path GET /patient/:id
 * @accessor api.functional.patient.findOne
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findOne(
  connection: IConnection,
  id: string,
): Promise<findOne.Output> {
  typia.assert<typeof id>(id);
  return true === connection.simulate
    ? findOne.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...findOne.METADATA,
        template: findOne.METADATA.path,
        path: findOne.path(id),
      });
}
export namespace findOne {
  export type Output = null | Patient_idstring.o2;

  export const METADATA = {
    method: 'GET',
    path: '/patient/:id',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/patient/${encodeURIComponent(id?.toString() ?? 'null')}`;
  export const random = (): Resolved<null | Patient_idstring.o2> =>
    typia.random<null | Patient_idstring.o2>();
  export const simulate = (connection: IConnection, id: string): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: 'application/json',
    });
    assert.param('id')(() => typia.assert(id));
    return random();
  };
}

/**
 * @controller PatientController.update
 * @path PATCH /patient/:id
 * @accessor api.functional.patient.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  updatePatientDto: update.Body,
): Promise<update.Output> {
  typia.assert<typeof id>(id);
  typia.assert<typeof updatePatientDto>(updatePatientDto);
  return true === connection.simulate
    ? update.simulate(connection, id, updatePatientDto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            'Content-Type': 'application/json',
          },
        },
        {
          ...update.METADATA,
          template: update.METADATA.path,
          path: update.path(id),
        },
        updatePatientDto,
      );
}
export namespace update {
  export type Body = UpdatePatientDto;
  export type Output = mongoose.UpdateWriteOpResult;

  export const METADATA = {
    method: 'PATCH',
    path: '/patient/:id',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/patient/${encodeURIComponent(id?.toString() ?? 'null')}`;
  export const random = (): Resolved<mongoose.UpdateWriteOpResult> =>
    typia.random<mongoose.UpdateWriteOpResult>();
  export const simulate = (
    connection: IConnection,
    id: string,
    updatePatientDto: Body,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: 'application/json',
    });
    assert.param('id')(() => typia.assert(id));
    assert.body(() => typia.assert(updatePatientDto));
    return random();
  };
}
