/**
 * @packageDocumentation
 * @module api.functional.observations.type.startDate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as endDate from './endDate/index';
