/**
 * @packageDocumentation
 * @module api.functional.documents.file
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { CreateFileDocumentDto } from '../../../structures/CreateFileDocumentDto';
import type { FormDataInput, IConnection } from '@nestia/fetcher';
import { NestiaSimulator, PlainFetcher } from '@nestia/fetcher';
import typia from 'typia';
import type { Resolved, tags } from 'typia';

/**
 * @controller DocumentsController.createFile
 * @path POST /documents/file
 * @accessor api.functional.documents.file.createFile
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createFile(
  connection: IConnection,
  createFileDocumentDto: createFile.Body,
): Promise<createFile.Output> {
  typia.assert<typeof createFileDocumentDto>(createFileDocumentDto);
  return true === connection.simulate
    ? createFile.simulate(connection, createFileDocumentDto)
    : PlainFetcher.fetch(
        connection,
        {
          ...createFile.METADATA,
          template: createFile.METADATA.path,
          path: createFile.path(),
        },
        createFileDocumentDto,
      );
}
export namespace createFile {
  export type Body = FormDataInput<CreateFileDocumentDto>;
  export type Output = {
    _id: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>;
  };

  export const METADATA = {
    method: 'POST',
    path: '/documents/file',
    request: {
      type: 'multipart/form-data',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => '/documents/file';
  export const random = (): Resolved<{
    _id: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>;
  }> =>
    typia.random<{
      _id: string & tags.Pattern<'^[0-9a-fA-F]{24}$'>;
    }>();
  export const simulate = (
    connection: IConnection,
    createFileDocumentDto: Body,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: 'application/json',
    });
    assert.body(() => typia.assert(createFileDocumentDto));
    return random();
  };
}
